dataset:
  train:
    dataroot_gt: data/sub_vsdrone/visdroneVSR/train/GT/ # path to GT (e.g., 000, 001, 002 ... )
    dataroot_lq: data/sub_vsdrone/visdroneVSR/train/BIx4/ # path to bicubic (e.g., 000, 001, 002 ... )
    meta_info_file: data/sub_vsdrone/visdroneVSR/train/meta_info_VisDrone_train.txt
    dataroot_flow:
    io_backend:
      type: disk
    num_frame: 3
    val_partition: 'REDS4'
    test_mode: False
    interval_list: [1]
    random_reverse: False
    gt_size: 256
    patch_size: [64,64]
    overlap: [10,10]
    use_hflip: True
    use_rot: False
    scale: 4
    remove_partition: True
  test:
    dataroot_gt: data/sub_vsdrone/visdroneVSR/val/GT/
    dataroot_lq: data/sub_vsdrone/visdroneVSR/val/BIx4/
    meta_info_file: data/sub_vsdrone/visdroneVSR/val/meta_info_VisDrone_val.txt
    io_backend:
      type: disk
    num_frame: 3
    val_partition: 'REDS4'
    test_mode: True
    patch_size: [ 256,256 ]
    overlap: [ 32,32 ]
    interval_list: [1]
    random_reverse: False
    gt_size: 256
    use_hflip: False
    use_rot: False
    scale: 4
    remove_partition: False